### ISSUE TITLE
docker build failed

### ISSUE THREAD

**Issue by xiayouran** [langwatch/langwatch#70]
When I run it locally, I follow the documentation：
**step1:** 

```bash 
cp langwatch/.env.example langwatch/.env
```

**step2:** 

```bash 
docker-compose up --build
```

then docker build failed!!!

error log:
```bash 
=> ERROR [app  5/10] RUN npm --prefix=langwatch ci                                                                                                    636.1s
------
 > [app  5/10] RUN npm --prefix=langwatch ci:
4.926 npm warn ERESOLVE overriding peer dependency
4.927 npm warn While resolving: flux@4.0.4
4.927 npm warn Found: react@18.2.0
4.927 npm warn node_modules/react
4.927 npm warn   react@"18.2.0" from the root project
4.927 npm warn   175 more (@ag-grid-community/react, @chakra-ui/accordion, ...)
4.927 npm warn
4.927 npm warn Could not resolve dependency:
4.927 npm warn peer react@"^15.0.2 || ^16.0.0 || ^17.0.0" from flux@4.0.4
4.927 npm warn node_modules/@microlink/react-json-view/node_modules/flux
4.927 npm warn   flux@"~4.0.1" from @microlink/react-json-view@1.23.1
4.927 npm warn   node_modules/@microlink/react-json-view
4.927 npm warn
4.927 npm warn Conflicting peer dependency: react@17.0.2
4.927 npm warn node_modules/react
4.927 npm warn   peer react@"^15.0.2 || ^16.0.0 || ^17.0.0" from flux@4.0.4
4.927 npm warn   node_modules/@microlink/react-json-view/node_modules/flux
4.927 npm warn     flux@"~4.0.1" from @microlink/react-json-view@1.23.1
4.927 npm warn     node_modules/@microlink/react-json-view
148.9 npm warn deprecated npmlog@5.0.1: This package is no longer supported.
252.8 npm warn deprecated gauge@3.0.2: This package is no longer supported.
281.9 npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
310.9 npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
635.7 npm error code 1
635.7 npm error path /app/langwatch/node_modules/bcrypt
635.7 npm error command failed
635.7 npm error command sh -c node-pre-gyp install --fallback-to-build
635.7 npm error Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/langwatch/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/app/langwatch/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=9 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
635.7 npm error node-pre-gyp info it worked if it ends with ok
635.7 npm error node-pre-gyp info using node-pre-gyp@1.0.11
635.7 npm error node-pre-gyp info using node@20.18.0 | linux | x64
635.7 npm error node-pre-gyp info check checked for "/app/langwatch/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" (not found)
635.7 npm error node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.1.1/bcrypt_lib-v5.1.1-napi-v3-linux-x64-musl.tar.gz
635.7 npm error node-pre-gyp ERR! install request to https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.1.1/bcrypt_lib-v5.1.1-napi-v3-linux-x64-musl.tar.gz failed, reason: connect ETIMEDOUT 20.205.243.166:443
635.7 npm error node-pre-gyp WARN Pre-built binaries not installable for bcrypt@5.1.1 and node@20.18.0 (node-v115 ABI, musl) (falling back to source compile with node-gyp)
635.7 npm error node-pre-gyp WARN Hit error request to https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.1.1/bcrypt_lib-v5.1.1-napi-v3-linux-x64-musl.tar.gz failed, reason: connect ETIMEDOUT 20.205.243.166:443
635.7 npm error gyp info it worked if it ends with ok
635.7 npm error gyp info using node-gyp@10.1.0
635.7 npm error gyp info using node@20.18.0 | linux | x64
635.7 npm error gyp info ok
635.7 npm error gyp info it worked if it ends with ok
635.7 npm error gyp info using node-gyp@10.1.0
635.7 npm error gyp info using node@20.18.0 | linux | x64
635.7 npm error gyp ERR! find Python
635.7 npm error gyp ERR! find Python Python is not set from command line or npm configuration
635.7 npm error gyp ERR! find Python Python is not set from environment variable PYTHON
635.7 npm error gyp ERR! find Python checking if "python3" can be used
635.7 npm error gyp ERR! find Python - executable path is ""
635.7 npm error gyp ERR! find Python - "" could not be run
635.7 npm error gyp ERR! find Python checking if "python" can be used
635.7 npm error gyp ERR! find Python - executable path is ""
635.7 npm error gyp ERR! find Python - "" could not be run
635.7 npm error gyp ERR! find Python
635.7 npm error gyp ERR! find Python **********************************************************
635.7 npm error gyp ERR! find Python You need to install the latest version of Python.
635.7 npm error gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
635.7 npm error gyp ERR! find Python you can try one of the following options:
635.7 npm error gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
635.7 npm error gyp ERR! find Python (accepted by both node-gyp and npm)
635.7 npm error gyp ERR! find Python - Set the environment variable PYTHON
635.7 npm error gyp ERR! find Python - Set the npm configuration variable python:
635.7 npm error gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
635.7 npm error gyp ERR! find Python For more information consult the documentation at:
635.7 npm error gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
635.7 npm error gyp ERR! find Python **********************************************************
635.7 npm error gyp ERR! find Python
635.7 npm error gyp ERR! configure error
635.7 npm error gyp ERR! stack Error: Could not find any Python installation to use
635.7 npm error gyp ERR! stack at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:306:11)
635.7 npm error gyp ERR! stack at PythonFinder.findPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:164:17)
635.7 npm error gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
635.7 npm error gyp ERR! stack at async configure (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:27:18)
635.7 npm error gyp ERR! stack at async run (/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
635.7 npm error gyp ERR! System Linux 3.10.0-957.el7.x86_64
635.7 npm error gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/langwatch/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/app/langwatch/node_modules/bcrypt/lib/binding/napi-v3" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
635.7 npm error gyp ERR! cwd /app/langwatch/node_modules/bcrypt
635.7 npm error gyp ERR! node -v v20.18.0
635.7 npm error gyp ERR! node-gyp -v v10.1.0
635.7 npm error gyp ERR! not ok
635.7 npm error node-pre-gyp ERR! build error
635.7 npm error node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/langwatch/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/app/langwatch/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=9 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
635.7 npm error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/langwatch/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
635.7 npm error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
635.7 npm error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
635.7 npm error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
635.7 npm error node-pre-gyp ERR! System Linux 3.10.0-957.el7.x86_64
635.7 npm error node-pre-gyp ERR! command "/usr/local/bin/node" "/app/langwatch/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
635.7 npm error node-pre-gyp ERR! cwd /app/langwatch/node_modules/bcrypt
635.7 npm error node-pre-gyp ERR! node -v v20.18.0
635.7 npm error node-pre-gyp ERR! node-pre-gyp -v v1.0.11
635.7 npm error node-pre-gyp ERR! not ok
635.7 npm notice
635.7 npm notice New minor version of npm available! 10.8.2 -> 10.9.0
635.7 npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
635.7 npm notice To update run: npm install -g npm@10.9.0
635.7 npm notice
635.7 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-10-08T07_10_41_851Z-debug-0.log
------
failed to solve: executor failed running [/bin/sh -c npm --prefix=langwatch ci]: exit code: 1
```

**Comment by rogeriochaves** [comment]
hey @xiayouran, checking it out now, likely a new npm dependency that for some reason requires python

**Comment by rogeriochaves** [comment]
@xiayouran actually bufferutils, the likely cause for the issue is [already an optional dependency](https://github.com/langwatch/langwatch/blob/b4e51acf4502e1de62ad147afcda768e4bc6398b/langwatch/package.json#L171), it should be not trying to build it from scratch, so that's weird, couldn't reproduce locally

I'll add python to the docker image anyway just in case then

Fixed by https://github.com/langwatch/langwatch/commit/6832140385d265f31065b770975b277f5a1bdbfe

Please pull and try again and let me know if that worked

**Comment by xiayouran** [comment]
@rogeriochaves good job👍but, I found another error, is it my network problem?
error info:
```bash
 => [langwatch_nlp internal] load build definition from Dockerfile                                                                                       0.1s
 => => transferring dockerfile: 91B                                                                                                                      0.0s
 => [langwatch_nlp internal] load .dockerignore                                                                                                          0.1s
 => => transferring context: 93B                                                                                                                         0.0s
 => [app internal] load build definition from Dockerfile                                                                                                 0.1s
 => => transferring dockerfile: 91B                                                                                                                      0.0s
 => [app internal] load .dockerignore                                                                                                                    0.1s
 => => transferring context: 93B                                                                                                                         0.0s
 => [langwatch_nlp internal] load metadata for docker.io/library/python:3.11-slim                                                                        2.3s
 => [app internal] load metadata for docker.io/library/node:20-alpine                                                                                    0.0s
 => [app  1/10] FROM docker.io/library/node:20-alpine                                                                                                    0.0s
 => [app internal] load build context                                                                                                                    0.6s
 => => transferring context: 72.57kB                                                                                                                     0.6s
 => CACHED [app  2/10] RUN apk --no-cache add curl python3 make gcc g++                                                                                  0.0s
 => CACHED [app  3/10] WORKDIR /app                                                                                                                      0.0s
 => CACHED [app  4/10] COPY langwatch/package.json langwatch/package-lock.json ./langwatch/                                                              0.0s
 => ERROR [app  5/10] RUN npm --prefix=langwatch ci                                                                                                   1074.3s
 => [langwatch_nlp 1/6] FROM docker.io/library/python:3.11-slim@sha256:5501a4fe605abe24de87c2f3d6cf9fd760354416a0cad0296cf284fddcdca9e2                  0.0s
 => [langwatch_nlp internal] load build context                                                                                                          0.1s
 => => transferring context: 6.34kB                                                                                                                      0.1s
 => CACHED [langwatch_nlp 2/6] WORKDIR /usr/src/app                                                                                                      0.0s
 => CACHED [langwatch_nlp 3/6] RUN pip install poetry                                                                                                    0.0s
 => CACHED [langwatch_nlp 4/6] COPY poetry.toml poetry.lock pyproject.toml .                                                                             0.0s
 => CACHED [langwatch_nlp 5/6] RUN poetry install                                                                                                        0.0s
 => CACHED [langwatch_nlp 6/6] COPY . .                                                                                                                  0.0s
 => [langwatch_nlp] exporting to image                                                                                                                   0.0s
 => => exporting layers                                                                                                                                  0.0s
 => => writing image sha256:2ddee20ac509a5b400f02714ab9f343119876f23786ac0ceae711c2977b658d7                                                             0.0s
 => => naming to docker.io/library/langwatch-langwatch_nlp                                                                                               0.0s
------
 > [app  5/10] RUN npm --prefix=langwatch ci:
7.450 npm warn ERESOLVE overriding peer dependency
7.451 npm warn While resolving: flux@4.0.4
7.451 npm warn Found: react@18.2.0
7.451 npm warn node_modules/react
7.451 npm warn   react@"18.2.0" from the root project
7.451 npm warn   175 more (@ag-grid-community/react, @chakra-ui/accordion, ...)
7.451 npm warn
7.451 npm warn Could not resolve dependency:
7.451 npm warn peer react@"^15.0.2 || ^16.0.0 || ^17.0.0" from flux@4.0.4
7.451 npm warn node_modules/@microlink/react-json-view/node_modules/flux
7.451 npm warn   flux@"~4.0.1" from @microlink/react-json-view@1.23.1
7.451 npm warn   node_modules/@microlink/react-json-view
7.451 npm warn
7.451 npm warn Conflicting peer dependency: react@17.0.2
7.451 npm warn node_modules/react
7.451 npm warn   peer react@"^15.0.2 || ^16.0.0 || ^17.0.0" from flux@4.0.4
7.451 npm warn   node_modules/@microlink/react-json-view/node_modules/flux
7.451 npm warn     flux@"~4.0.1" from @microlink/react-json-view@1.23.1
7.451 npm warn     node_modules/@microlink/react-json-view
433.3 npm warn deprecated npmlog@5.0.1: This package is no longer supported.
769.7 npm warn deprecated gauge@3.0.2: This package is no longer supported.
789.1 npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
858.1 npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
1073.7 npm error code ETIMEDOUT
1073.7 npm error syscall read
1073.7 npm error errno -110
1073.7 npm error network read ETIMEDOUT
1073.7 npm error network This is a problem related to network connectivity.
1073.7 npm error network In most cases you are behind a proxy or have bad network settings.
1073.7 npm error network
1073.7 npm error network If you are behind a proxy, please make sure that the
1073.7 npm error network 'proxy' config is set properly.  See: 'npm help config'
1073.8 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-10-09T09_15_09_505Z-debug-0.log
------
failed to solve: executor failed running [/bin/sh -c npm --prefix=langwatch ci]: exit code: 146
```

**Comment by hteeyeoh** [comment]
After I managed to run the container with docker-compose up --build, after close the containers. and i try to up again the containers it failed. Not sure why? It even breaks my docker in my system, Now i cant even bring up my other container as well.
Traceback (most recent call last):
  File "/home/intel/.local/lib/python3.10/site-packages/requests/adapters.py", line 633, in send
    conn = self.get_connection_with_tls_context(
  File "/home/intel/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in get_connection_with_tls_context
    conn = self.poolmanager.connection_from_host(
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 245, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 257, in connection_from_context
    raise URLSchemeUnknown(scheme)
urllib3.exceptions.URLSchemeUnknown: Not supported URL scheme http+docker

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/intel/.local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/intel/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/intel/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/intel/.local/lib/python3.10/site-packages/requests/adapters.py", line 637, in send
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Not supported URL scheme http+docker

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker

**Comment by rogeriochaves** [comment]
@xiayouran indeed, it doesn't seem to have a clear reason for npm install to throw timeouts here, have you tried multiple times and it always times out? are you perhaps behind a proxy as the message suggests?

if just network is the issue, could you try changing the docker image to increase the npm timeout and see if it works? https://stackoverflow.com/questions/51434006/how-to-fix-timeout-for-packages-on-npm-install

**Comment by xiayouran** [comment]
Hey @rogeriochaves , I solved the network problem, and then a new problem came up while building:
```bash
[+] Running 1/1
 ✔ langevals Pulled                                                                                                                                      3.3s
[+] Building 37.2s (13/24)
 => [langwatch_nlp internal] load build definition from Dockerfile                                                                                       0.0s
 => => transferring dockerfile: 91B                                                                                                                      0.0s
 => [app internal] load build definition from Dockerfile                                                                                                 0.0s
 => => transferring dockerfile: 91B                                                                                                                      0.0s
 => [langwatch_nlp internal] load .dockerignore                                                                                                          0.0s
 => => transferring context: 93B                                                                                                                         0.0s
 => [app internal] load .dockerignore                                                                                                                    0.0s
 => => transferring context: 93B                                                                                                                         0.0s
 => [langwatch_nlp internal] load metadata for docker.io/library/python:3.11-slim                                                                        0.0s
 => [langwatch_nlp 1/6] FROM docker.io/library/python:3.11-slim                                                                                          0.0s
 => [langwatch_nlp internal] load build context                                                                                                          0.0s
 => => transferring context: 6.47kB                                                                                                                      0.0s
 => CACHED [langwatch_nlp 2/6] WORKDIR /usr/src/app                                                                                                      0.0s
 => ERROR [langwatch_nlp 3/6] RUN pip install poetry                                                                                                    36.7s
 => [app internal] load metadata for docker.io/library/node:20-alpine                                                                                    0.0s
 => [app internal] load build context                                                                                                                    0.1s
 => => transferring context: 74.07kB                                                                                                                     0.1s
 => CACHED [app  1/10] FROM docker.io/library/node:20-alpine                                                                                             0.0s
 => CANCELED [app  2/10] RUN apk --no-cache add curl python3 make gcc g++                                                                               36.9s
------
 > [langwatch_nlp 3/6] RUN pip install poetry:
3.667 Collecting poetry
4.445   Downloading poetry-1.8.3-py3-none-any.whl.metadata (6.8 kB)
4.902 Collecting build<2.0.0,>=1.0.3 (from poetry)
5.186   Downloading build-1.2.2.post1-py3-none-any.whl.metadata (6.5 kB)
...
34.58 Collecting cffi>=1.12 (from cryptography>=2.0->SecretStorage>=3.2->keyring<25.0.0,>=24.0.0->poetry)
34.66   Downloading cffi-1.17.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
34.87 Collecting pycparser (from cffi>=1.12->cryptography>=2.0->SecretStorage>=3.2->keyring<25.0.0,>=24.0.0->poetry)
35.01   Downloading pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
35.23 Downloading poetry-1.8.3-py3-none-any.whl (249 kB)
35.24 ERROR: Exception:
35.24 Traceback (most recent call last):
35.24   File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
35.24     status = run_func(*args)
35.24              ^^^^^^^^^^^^^^^
35.24   File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
35.24     return func(self, options, args)
35.24            ^^^^^^^^^^^^^^^^^^^^^^^^^
35.24   File "/usr/local/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
35.24     requirement_set = resolver.resolve(
35.24                       ^^^^^^^^^^^^^^^^^
35.24   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 179, in resolve
35.24     self.factory.preparer.prepare_linked_requirements_more(reqs)
35.24   File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 552, in prepare_linked_requirements_more
35.24     self._complete_partial_requirements(
35.24   File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 467, in _complete_partial_requirements
35.24     for link, (filepath, _) in batch_download:
35.24   File "/usr/local/lib/python3.11/site-packages/pip/_internal/network/download.py", line 183, in __call__
35.24     for chunk in chunks:
35.24   File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/progress_bars.py", line 52, in _rich_progress_bar
35.24     with progress:
35.24   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/rich/progress.py", line 1169, in __enter__
35.24     self.start()
35.24   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/rich/progress.py", line 1160, in start
35.24     self.live.start(refresh=True)
35.24   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/rich/live.py", line 132, in start
35.24     self._refresh_thread.start()
35.24   File "/usr/local/lib/python3.11/threading.py", line 964, in start
35.24     _start_new_thread(self._bootstrap, ())
35.24 RuntimeError: can't start new thread
35.95
35.95 [notice] A new release of pip is available: 24.0 -> 24.2
35.95 [notice] To update, run: pip install --upgrade pip
------
failed to solve: executor failed running [/bin/sh -c pip install poetry]: exit code: 2
```

**Comment by unfixa1** [comment]
node-gyp requires Python environment, make sure Python is installed in the Docker image. You can add the following line to the Dockerfile:
RUN apt-get update && apt-get install -y python3
Make sure Python can be found when building, you may need to set the environment variable:
ENV PYTHON=python3

In addition, you can use [Servbay](servbay.com) to check your development environment, which is better than Docker on Mac. You can deploy the development environment you need with one click, and you can ensure that there is no compatibility conflict in the environment

**Comment by SaiCharanChetpelly31** [comment]
Hi @xiayouran ,

I'm trying to run the project locally using Docker, but I'm facing some errors related to Poetry. Could you please let me know how you managed to run it locally?

Thanks!

**Comment by xiayouran** [comment]
@SaiCharanChetpelly31 I also used the docker container to run it, but I didn't run it, and encountered problems in the build phase.

**Comment by rogeriochaves** [comment]
hey @SaiCharanChetpelly31, @xiayouran unfortunately we couldn't reproduce this problem locally on Mac M1 family and Ubuntu machines, could you please share what is your OS and device?

also, please try pulling the latest version to see if the problem continues

**Comment by xiayouran** [comment]
Hi @rogeriochaves , I pull the latest version(commit-id: **f3dff1de6f60a6ad3c0d63d787794e9b1496af6b**)，same issue.
my machine information:
```bash
# OS
CentOS Linux release 7.6.1810 (Core)

# CPU
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                96
On-line CPU(s) list:   0-95
Thread(s) per core:    2
Core(s) per socket:    24
Socket(s):             2
NUMA node(s):          8
Vendor ID:             HygonGenuine
CPU family:            24
Model:                 0
Model name:            Hygon C86 7165 24-core Processor
Stepping:              1
CPU MHz:               1200.000
```

**Comment by xiayouran** [comment]
> Hi @rogeriochaves , I pull the latest version(commit-id: **[f3dff1d](https://github.com/langwatch/langwatch/commit/f3dff1de6f60a6ad3c0d63d787794e9b1496af6b)**)，same issue. my machine information:
> 
> ```shell
> # OS
> CentOS Linux release 7.6.1810 (Core)
> 
> # CPU
> Architecture:          x86_64
> CPU op-mode(s):        32-bit, 64-bit
> Byte Order:            Little Endian
> CPU(s):                96
> On-line CPU(s) list:   0-95
> Thread(s) per core:    2
> Core(s) per socket:    24
> Socket(s):             2
> NUMA node(s):          8
> Vendor ID:             HygonGenuine
> CPU family:            24
> Model:                 0
> Model name:            Hygon C86 7165 24-core Processor
> Stepping:              1
> CPU MHz:               1200.000
> ```

Hey @rogeriochaves , I tried to run it on another machine and it worked! The two machines have the same OS version, the difference is the CPU, CPU(`Intel(R) Xeon(R) Silver 4216`) is running OK, CPU(`Hygon C86 7165 24-core Processor`) failed, but their architecture is `x86_64`.
